export const REPORTING_CONFIG = 'REPORTING_CONFIG';
export const REPORT_REPOSITORY = 'REPORT_REPOSITORY';
export const REPORT_CACHE = 'REPORT_CACHE';
export const EXPORT_RATE_LIMITER = 'EXPORT_RATE_LIMITER';
export const REPORT_AUDIT_REPOSITORY = 'REPORT_AUDIT_REPOSITORY';
export const REPORT_SERVICE = 'REPORT_SERVICE';
