export const MEDIA_CONFIG = 'MEDIA_CONFIG';
export const CHANNEL_REPOSITORY = 'CHANNEL_REPOSITORY';
export const SESSION_REPOSITORY = 'SESSION_REPOSITORY';
export const SESSION_CACHE = 'SESSION_CACHE';
export const MEDIA_ROUTER = 'MEDIA_ROUTER';
export const CHANNEL_MANAGER = 'CHANNEL_MANAGER';
export const STREAM_MANAGER = 'STREAM_MANAGER';
export const SIGNALING_GATEWAY = 'SIGNALING_GATEWAY';
