/**
 * Telemetry metrics — minimal Prometheus counters/gauges for the telemetry
 * pipeline (Sprint D §33).
 *
 * Deliberately small: a single registry per process + the handful of metrics
 * the telemetry vertical needs (gateway connections, Kafka produce/consume
 * outcomes, GPS processing, WebSocket fan-out). No histograms-beyond-latency,
 * no exemplars, no push-gateway — the exposition endpoint is served by
 * `MetricsController` (GET /metrics).
 *
 * All labels are bounded enums (topic/result/class) — no unbounded label
 * values (IMEIs, tenant ids, vehicle ids are NEVER label values), so the
 * registry cannot cardinality-explode.
 */
import { Counter, Gauge, Histogram, Registry, collectDefaultMetrics } from 'prom-client';

export interface TelemetryMetrics {
  readonly registry: Registry;

  // --- Gateway (device connections + registry) -----------------------------
  /** Connection attempts by outcome (accepted | rejected_pool_full). */
  readonly gatewayConnections: Counter<string>;
  /** Sessions closed as duplicates (new connection replaced old). */
  readonly gatewayDuplicateConnections: Counter<string>;
  /** Device-registry resolves by outcome (hit_l1 | hit_l2 | miss | error). */
  readonly registryResolves: Counter<string>;
  /** Kafka messages produced by topic × outcome (ok | error). */
  readonly kafkaProduced: Counter<string>;

  // --- Kafka consumer (gps-engine) ------------------------------------------
  /** Messages consumed by topic × outcome (processed | duplicate | dlq | dropped). */
  readonly kafkaConsumed: Counter<string>;
  /** Processing retries by topic. */
  readonly kafkaRetries: Counter<string>;
  /** Messages sent to the DLQ by topic. */
  readonly dlqMessages: Counter<string>;
  /** Position processing latency (parse→persist→broadcast), seconds. */
  readonly processingLatency: Histogram<string>;

  // --- GPS pipeline ----------------------------------------------------------
  /** Positions by outcome (accepted | rejected | stale | out_of_order | duplicate). */
  readonly positions: Counter<string>;

  // --- WebSocket -------------------------------------------------------------
  /** Currently connected WS clients. */
  readonly wsClients: Gauge<string>;
  /** Active room subscriptions. */
  readonly wsSubscriptions: Gauge<string>;
  /** Position updates dropped by coalescing (back-pressure). */
  readonly wsDroppedUpdates: Counter<string>;

  // --- Alarm/Event engine (notification-service) — Sprint G ------------------
  /** FleetEvents received by source (position | session | tracking). */
  readonly eventsReceived: Counter<string>;
  /** FleetEvents processed successfully by source. */
  readonly eventsProcessed: Counter<string>;
  /** FleetEvent processing failures by source. */
  readonly eventsFailed: Counter<string>;
  /** Duplicate FleetEvents suppressed by eventId idempotency, by source. */
  readonly duplicateEvents: Counter<string>;
  /** Rule evaluations run by outcome (evaluated). */
  readonly rulesEvaluated: Counter<string>;
  /** Alarm occurrences opened by type. */
  readonly alarmsOpened: Counter<string>;
  /** Alarm occurrences acknowledged by actor kind (user | system). */
  readonly alarmsAcknowledged: Counter<string>;
  /** Alarm occurrences resolved by actor kind (user | system). */
  readonly alarmsResolved: Counter<string>;

  // --- Notification Center (notification-service) — Sprint H ----------------
  /** Notifications created (per-user records) by event type. */
  readonly notificationsCreated: Counter<string>;
  /** Channel dispatches attempted by channel. */
  readonly notificationsDispatched: Counter<string>;
  /** Channel deliveries accepted by the provider by channel. */
  readonly notificationsSent: Counter<string>;
  /** Provider-confirmed deliveries by channel. */
  readonly notificationsDelivered: Counter<string>;
  /** Terminal delivery failures by channel. */
  readonly notificationsFailed: Counter<string>;
  /** Retry attempts executed by channel. */
  readonly notificationsRetried: Counter<string>;
  /** Deliveries abandoned after retry exhaustion by channel. */
  readonly notificationsDlq: Counter<string>;
  /** Duplicate notification sources suppressed by idempotency, by event type. */
  readonly notificationsDeduplicated: Counter<string>;
  /** Dispatches suppressed by the per-tenant/user/channel rate limiter, by channel. */
  readonly notificationsRateLimited: Counter<string>;
  /** Provider-level outcomes by channel × result (success | failure). */
  readonly notificationProvider: Counter<string>;

  // --- Geofence + advanced tracking (Sprint I) ------------------------------
  /** Geofence lifecycle mutations by action (bounded CRUD verb enum). */
  readonly geofenceMutations: Counter<string>;
  /** Geofence FleetEvents generated by the evaluator (entered | exited | dwell). */
  readonly geofenceEvents: Counter<string>;
  /** Geofence evaluation failures (spatial query / state errors). */
  readonly geofenceEvalErrors: Counter<string>;
  /** History queries by outcome (ok | invalid). */
  readonly historyQueries: Counter<string>;
  /** Map-match requests by outcome (success | failure | fallback). */
  readonly mapMatchRequests: Counter<string>;

  // --- Reporting & analytics (reporting-service) — Sprint J -----------------
  /** Report requests by report (bounded enum) × outcome (ok | error). */
  readonly reportRequests: Counter<string>;
  /** Report query duration, seconds (per report kind). */
  readonly reportDuration: Histogram<string>;
  /** CSV export requests by outcome (ok | rate_limited | error). */
  readonly reportExports: Counter<string>;
  /** Report cache lookups by outcome (hit | miss). */
  readonly reportCache: Counter<string>;
}

export interface TelemetryMetricsOptions {
  /** Metric name prefix, e.g. 'fleetvision' → fleetvision_kafka_produced_total. */
  readonly prefix?: string;
  /** Include Node.js default metrics (process/event-loop). Default true. */
  readonly defaultMetrics?: boolean;
}

const GATEWAY_TOPICS = [
  'position',
  'alarm',
  'device',
  'commandAck',
  'session',
  'tracking',
] as const;
const CONSUME_TOPICS = ['position', 'session', 'tracking'] as const;
const EVENT_SOURCES = ['position', 'session', 'tracking'] as const;

/** Create the telemetry metric set on a fresh registry. */
export function createTelemetryMetrics(options: TelemetryMetricsOptions = {}): TelemetryMetrics {
  const prefix = options.prefix ?? 'fleetvision';
  const registry = new Registry();
  if (options.defaultMetrics !== false) {
    collectDefaultMetrics({ register: registry, prefix: `${prefix}_node` });
  }

  const labelNames = ['topic', 'result'] as const;

  const gatewayConnections = new Counter({
    name: `${prefix}_gateway_connections_total`,
    help: 'Device connection attempts by outcome.',
    labelNames: ['result'],
    registers: [registry],
  });

  const gatewayDuplicateConnections = new Counter({
    name: `${prefix}_gateway_duplicate_connections_total`,
    help: 'Sessions closed because a newer connection for the same device replaced them.',
    labelNames: ['scope'],
    registers: [registry],
  });

  const registryResolves = new Counter({
    name: `${prefix}_registry_resolves_total`,
    help: 'Device-registry resolutions by cache tier / outcome.',
    labelNames: ['result'],
    registers: [registry],
  });

  const kafkaProduced = new Counter({
    name: `${prefix}_kafka_produced_total`,
    help: 'Kafka messages produced by topic and outcome.',
    labelNames: [...labelNames],
    registers: [registry],
  });

  const kafkaConsumed = new Counter({
    name: `${prefix}_kafka_consumed_total`,
    help: 'Kafka messages consumed by topic and outcome.',
    labelNames: [...labelNames],
    registers: [registry],
  });

  const kafkaRetries = new Counter({
    name: `${prefix}_kafka_retries_total`,
    help: 'In-process message processing retries by topic.',
    labelNames: ['topic'],
    registers: [registry],
  });

  const dlqMessages = new Counter({
    name: `${prefix}_dlq_messages_total`,
    help: 'Messages routed to the dead-letter topic by original topic.',
    labelNames: ['topic'],
    registers: [registry],
  });

  const processingLatency = new Histogram({
    name: `${prefix}_processing_latency_seconds`,
    help: 'End-to-end position processing latency (consumer → pipeline).',
    labelNames: ['topic'],
    buckets: [0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5],
    registers: [registry],
  });

  const positions = new Counter({
    name: `${prefix}_positions_total`,
    help: 'Positions processed by outcome.',
    labelNames: ['result'],
    registers: [registry],
  });

  const wsClients = new Gauge({
    name: `${prefix}_ws_clients`,
    help: 'Currently connected WebSocket clients.',
    registers: [registry],
  });

  const wsSubscriptions = new Gauge({
    name: `${prefix}_ws_subscriptions`,
    help: 'Active WebSocket room subscriptions.',
    registers: [registry],
  });

  const wsDroppedUpdates = new Counter({
    name: `${prefix}_ws_dropped_updates_total`,
    help: 'Position updates superseded (dropped) by coalescing back-pressure.',
    registers: [registry],
  });

  // --- Alarm/Event engine (Sprint G) ----------------------------------------
  const eventsReceived = new Counter({
    name: `${prefix}_events_received_total`,
    help: 'FleetEvents received by source.',
    labelNames: ['source'],
    registers: [registry],
  });
  const eventsProcessed = new Counter({
    name: `${prefix}_events_processed_total`,
    help: 'FleetEvents processed successfully by source.',
    labelNames: ['source'],
    registers: [registry],
  });
  const eventsFailed = new Counter({
    name: `${prefix}_events_failed_total`,
    help: 'FleetEvent processing failures by source.',
    labelNames: ['source'],
    registers: [registry],
  });
  const duplicateEvents = new Counter({
    name: `${prefix}_duplicate_events_total`,
    help: 'Duplicate FleetEvents suppressed by eventId idempotency, by source.',
    labelNames: ['source'],
    registers: [registry],
  });
  const rulesEvaluated = new Counter({
    name: `${prefix}_rules_evaluated_total`,
    help: 'Alarm rule evaluations run.',
    registers: [registry],
  });
  const alarmsOpened = new Counter({
    name: `${prefix}_alarms_opened_total`,
    help: 'Alarm occurrences opened by type.',
    labelNames: ['type'],
    registers: [registry],
  });
  const alarmsAcknowledged = new Counter({
    name: `${prefix}_alarms_acknowledged_total`,
    help: 'Alarm occurrences acknowledged by actor kind.',
    labelNames: ['actor'],
    registers: [registry],
  });
  const alarmsResolved = new Counter({
    name: `${prefix}_alarms_resolved_total`,
    help: 'Alarm occurrences resolved by actor kind.',
    labelNames: ['actor'],
    registers: [registry],
  });

  // --- Notification Center (Sprint H) ---------------------------------------
  const NOTIF_CHANNELS = ['websocket', 'in_app', 'email', 'sms', 'push', 'webhook'] as const;
  const notificationsCreated = new Counter({
    name: `${prefix}_notifications_created_total`,
    help: 'Notifications created by event type.',
    labelNames: ['type'],
    registers: [registry],
  });
  const notificationsDispatched = new Counter({
    name: `${prefix}_notifications_dispatched_total`,
    help: 'Notification channel dispatches attempted by channel.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationsSent = new Counter({
    name: `${prefix}_notifications_sent_total`,
    help: 'Notification deliveries accepted by the provider by channel.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationsDelivered = new Counter({
    name: `${prefix}_notifications_delivered_total`,
    help: 'Provider-confirmed notification deliveries by channel.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationsFailed = new Counter({
    name: `${prefix}_notifications_failed_total`,
    help: 'Terminal notification delivery failures by channel.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationsRetried = new Counter({
    name: `${prefix}_notifications_retried_total`,
    help: 'Notification delivery retry attempts by channel.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationsDlq = new Counter({
    name: `${prefix}_notifications_dlq_total`,
    help: 'Notification deliveries abandoned after retry exhaustion by channel.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationsDeduplicated = new Counter({
    name: `${prefix}_notifications_deduplicated_total`,
    help: 'Duplicate notification sources suppressed by idempotency, by event type.',
    labelNames: ['type'],
    registers: [registry],
  });
  const notificationsRateLimited = new Counter({
    name: `${prefix}_notifications_rate_limited_total`,
    help: 'Dispatches suppressed by the per-tenant/user/channel rate limiter.',
    labelNames: ['channel'],
    registers: [registry],
  });
  const notificationProvider = new Counter({
    name: `${prefix}_notification_provider_total`,
    help: 'Notification provider outcomes by channel × result.',
    labelNames: ['channel', 'result'],
    registers: [registry],
  });

  // --- Geofence + advanced tracking (Sprint I) ------------------------------
  const GEOFENCE_ACTIONS = [
    'created',
    'updated',
    'archived',
    'deleted',
    'activated',
    'deactivated',
    'assigned',
    'unassigned',
  ] as const;
  const GEOFENCE_EVENT_TYPES = ['entered', 'exited', 'dwell'] as const;
  const geofenceMutations = new Counter({
    name: `${prefix}_geofence_mutations_total`,
    help: 'Geofence lifecycle mutations by action.',
    labelNames: ['action'],
    registers: [registry],
  });
  const geofenceEvents = new Counter({
    name: `${prefix}_geofence_events_total`,
    help: 'Geofence FleetEvents generated by the evaluator.',
    labelNames: ['type'],
    registers: [registry],
  });
  const geofenceEvalErrors = new Counter({
    name: `${prefix}_geofence_eval_errors_total`,
    help: 'Geofence evaluation failures.',
    registers: [registry],
  });
  const historyQueries = new Counter({
    name: `${prefix}_history_queries_total`,
    help: 'Vehicle history queries by outcome.',
    labelNames: ['result'],
    registers: [registry],
  });
  const mapMatchRequests = new Counter({
    name: `${prefix}_map_match_requests_total`,
    help: 'Map-match requests by outcome.',
    labelNames: ['result'],
    registers: [registry],
  });

  // --- Reporting & analytics (Sprint J) --------------------------------------
  const REPORT_KINDS = [
    'fleet-overview',
    'vehicle-utilization',
    'trips',
    'distance',
    'speed',
    'idle-parking',
    'alarms',
    'alarm-trend',
    'geofences',
    'activity',
  ] as const;
  const reportRequests = new Counter({
    name: `${prefix}_report_requests_total`,
    help: 'Report requests by report and outcome.',
    labelNames: ['report', 'result'],
    registers: [registry],
  });
  const reportDuration = new Histogram({
    name: `${prefix}_report_duration_seconds`,
    help: 'Report query duration in seconds.',
    labelNames: ['report'],
    buckets: [0.005, 0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10],
    registers: [registry],
  });
  const reportExports = new Counter({
    name: `${prefix}_report_exports_total`,
    help: 'CSV export requests by outcome.',
    labelNames: ['result'],
    registers: [registry],
  });
  const reportCache = new Counter({
    name: `${prefix}_report_cache_total`,
    help: 'Report cache lookups by outcome.',
    labelNames: ['result'],
    registers: [registry],
  });

  // Pre-seed the bounded label domains so early scrapes expose complete series.
  for (const result of ['accepted', 'rejected_pool_full']) gatewayConnections.inc({ result }, 0);
  for (const scope of ['local', 'cross_instance']) {
    gatewayDuplicateConnections.inc({ scope }, 0);
  }
  for (const result of ['hit_l1', 'hit_l2', 'miss', 'error']) registryResolves.inc({ result }, 0);
  for (const topic of GATEWAY_TOPICS) {
    for (const result of ['ok', 'error']) kafkaProduced.inc({ topic, result }, 0);
  }
  for (const topic of CONSUME_TOPICS) {
    for (const result of ['processed', 'duplicate', 'dlq', 'dropped']) {
      kafkaConsumed.inc({ topic, result }, 0);
    }
    kafkaRetries.inc({ topic }, 0);
    dlqMessages.inc({ topic }, 0);
    processingLatency.observe({ topic }, 0);
  }
  for (const result of ['accepted', 'rejected', 'stale', 'out_of_order', 'duplicate']) {
    positions.inc({ result }, 0);
  }
  for (const source of EVENT_SOURCES) {
    eventsReceived.inc({ source }, 0);
    eventsProcessed.inc({ source }, 0);
    eventsFailed.inc({ source }, 0);
    duplicateEvents.inc({ source }, 0);
  }
  rulesEvaluated.inc(0);
  for (const actor of ['user', 'system']) {
    alarmsAcknowledged.inc({ actor }, 0);
    alarmsResolved.inc({ actor }, 0);
  }
  for (const channel of NOTIF_CHANNELS) {
    notificationsDispatched.inc({ channel }, 0);
    notificationsSent.inc({ channel }, 0);
    notificationsDelivered.inc({ channel }, 0);
    notificationsFailed.inc({ channel }, 0);
    notificationsRetried.inc({ channel }, 0);
    notificationsDlq.inc({ channel }, 0);
    notificationsRateLimited.inc({ channel }, 0);
    for (const result of ['success', 'failure']) {
      notificationProvider.inc({ channel, result }, 0);
    }
  }
  notificationsCreated.inc(0);
  notificationsDeduplicated.inc(0);
  for (const action of GEOFENCE_ACTIONS) geofenceMutations.inc({ action }, 0);
  for (const type of GEOFENCE_EVENT_TYPES) geofenceEvents.inc({ type }, 0);
  geofenceEvalErrors.inc(0);
  for (const result of ['ok', 'invalid']) historyQueries.inc({ result }, 0);
  for (const result of ['success', 'failure', 'fallback']) mapMatchRequests.inc({ result }, 0);
  for (const report of REPORT_KINDS) {
    for (const result of ['ok', 'error']) reportRequests.inc({ report, result }, 0);
    reportDuration.observe({ report }, 0);
  }
  for (const result of ['ok', 'rate_limited', 'error']) reportExports.inc({ result }, 0);
  for (const result of ['hit', 'miss']) reportCache.inc({ result }, 0);

  return {
    registry,
    gatewayConnections,
    gatewayDuplicateConnections,
    registryResolves,
    kafkaProduced,
    kafkaConsumed,
    kafkaRetries,
    dlqMessages,
    processingLatency,
    positions,
    wsClients,
    wsSubscriptions,
    wsDroppedUpdates,
    eventsReceived,
    eventsProcessed,
    eventsFailed,
    duplicateEvents,
    rulesEvaluated,
    alarmsOpened,
    alarmsAcknowledged,
    alarmsResolved,
    notificationsCreated,
    notificationsDispatched,
    notificationsSent,
    notificationsDelivered,
    notificationsFailed,
    notificationsRetried,
    notificationsDlq,
    notificationsDeduplicated,
    notificationsRateLimited,
    notificationProvider,
    geofenceMutations,
    geofenceEvents,
    geofenceEvalErrors,
    historyQueries,
    mapMatchRequests,
    reportRequests,
    reportDuration,
    reportExports,
    reportCache,
  };
}
